version: '3.3'

services:
  nginx-proxy:
    build: ./nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    links:
      - "spiderapi:spiderapi"
    
  spiderapi:
    build: ./spiderapi
    volumes:
      - type: bind
        source: ${PWD}/research.sqlite
        target: /usr/data/research.sqlite
